 USE scrumptious_coffee_db;
DROP TABLE products;
CREATE TABLE products(
products_id int AUTO_INCREMENT PRIMARY KEY,
name varchar(255) not null,
image_url varchar(255) not null,
description varchar(255) not null,
store_quantity int not null,
price_per_pound decimal(4,2),
roast varchar(255) not null,
location varchar(255) not null
);
INSERT INTO products(name,image_url,description,store_quantity,price_per_pound,roast,location)
VALUES
("Hawaiian Kona Coffee","https://i.imgur.com/RiHhhZi.jpg","Well-balanced with a medium body, our traditional style Kona Coffee blend brings a taste of Hawaii’s Big Island to your kitchen. Our Kona is light and sweet with a hint of fruity flavor." ,
12,12.99,'Medium','North America'),
('Mocha Java Coffee','https://i.imgur.com/RHm8Tck.jpg',"Perhaps the most famous blend of coffee beans, Mocha Java includes Arabian (Yemen) Mocha coffee and Indonesian Java Arabica coffee, two coffees with complementary characteristics. Give our version of one of the world's first blends a try.",
15,12.77,'Medium','Asia'),
('Kenya AA Coffee','https://i.imgur.com/yokkvP1.jpg',"The best Kenya AA coffees exhibit a full body and strong, rich taste with a pleasant acidity that some say provides the world's brightest coffee. If you like medium-roasted, slightly fruity blends, be sure to give this one a try.",
15,13.33, 'Dark', 'Africa' ),
("Tanzanian Peaberry Coffee","https://i.imgur.com/qxRcvQ7.jpg","This delicate, light roast coffee provides an aroma that is floral and complex. Our Tanzanian coffee exhibits hints of pineapple, citrus, and coconut.",
12,11.70, 'Light', 'Africa'),
("Nicaraguan Coffee","https://i.imgur.com/oZdExjf.jpg","Be bold and try our dark roast Nicaraguan coffee. The smooth body and moderate acidity brighten the chocolate and bittersweet notes.",
12,21.35,'Dark','Central America'),
("Ethiopian Harrar Coffee","https://i.imgur.com/LeD8KOU.jpg","Edgy and bold, Ethiopian Harrar displays a complexity of spice tones and fruitiness that is reminiscent of your favorite red wine. Our Harrar is a brilliant dark roast perfect for a bright pick me up on a busy afternoon.",
15,13.04, 'Dark', 'Africa'),
("Ethiopian Yirgacheffe Coffee","https://i.imgur.com/AUD1AHR.jpg","This bright and acidic coffee comes across the palate with an intense, clean, and floral flavor. This Ethiopian blend comes from the town of Yirga Chefe in southern Ethiopia, just south of the Bale Mountains.",
15,16.46,'Light', 'Africa'),
("Guatemala Antigua Coffee","https://i.imgur.com/7tkdZxw.jpg","Our Guatemalan coffee is naturally smooth and delicious, with hints of chocolate-sweetness. This coffee comes from the volcanic ash enriched earth that makes Guatemalan coffee so flavorful.",
10,13.56,'Dark','Central America'),
("Brazilian Santos","https://i.imgur.com/TL17WhP.jpg",'Brazil is known the world over as one of the most prolific coffee producers. This is easily the “softest” coffee we offer, and many people are surprised by how smooth and light it is on their palate.',
15,19.95,'Medium','Central America'),
('Colombian Supremo','https://i.imgur.com/ykByB7d.jpg','This coffee is what off-the-shelf brands are trying to emulate when they offer “100% Colombian” blends, but not one of them comes close to the quality of our fresh roasted Colombian Supremo beans. This Colombian coffee is truly a classic with low acidity and the perfect balance of sweetness.',
10,21.85,'Dark','South America'),
('Peru High Grown','https://i.imgur.com/jyadr64.jpg','This versatile coffee bean is grown in high-altitude regions in Peru. Moderately acidic with a soft body and flavor, this bean is ideal as a blending coffee or all on its own.',
14,18.54,'Light','South America'),
('Jamaica Blue Mountain','https://i.imgur.com/r2BKFMB.jpg','Grown in the Clydesdale Estate on the southern slopes of the Jamaican Blue Mountains, this coffee is lightly roasted to retain its vibrant notes of chocolate and honey. Our sophisticated Jamaican Blue Mountain blend has an excellent full-body and smooth profile.',
14,13.54,'Light','Central America'),
('Panama Boquete','https://i.imgur.com/Z5pikfP.jpg','Panama Boquete has flown under the radar for far too long. Our Panama Boquete beans are a shining example of superior quality coffee with a complex, rewarding flavor profile unlike any other.',
12 , 12.73,'Medium','Central America'),
('Costa Rican Tarrazu','https://i.imgur.com/qhL8mk4.jpg',"Costa Rica is regarded as one of the world's premier coffee-growing regions due to its volcanic soil and ideal drainage. As a result, this lightly roasted coffee creates a sweet cup with a fruity aroma.",
10, 18.24, 'Dark', 'Central America'),
('Estate Java','https://i.imgur.com/6qJVqhL.jpg','Grown on the island of Java, the name of this bean has become synonymous with coffee. Like many other Indonesian varietals, this bean is low in acidity and produces a rich, buttery brew with a sweet aroma.',
13,16.34,'Medium','Asia'),
('Sumatra Mandheling','https://i.imgur.com/r9SpCpz.jpg','A staple of coffee shops throughout the world, Sumatra has an earthy, chocolaty flavor and is considered to be among the finest beans available.',
20,19.54,'Medium','Asia'),
('Sulawesi Kalossi','https://i.imgur.com/OLxngwd.jpg','On the Indonesian island of Sulawesi, not far from the village Kalossi, the high-altitude volcanic soil is perfect for growing coffee. Known for its velvety body, this bean features rich, earthy flavor notes and a heady, exotic aroma.',
12,14.12,'Medium','Asia'),
('Danish Blend','https://i.imgur.com/BB4seBp.jpg','Denmark is the home of Kaffeepause, a break in the day used to rest and sip on our favorite treat: coffee! Not only do we support this tradition, we have created a blend of beans to celebrate it.',
16,18.34,'Light','South America'),
('Bali Blue Moon','https://i.imgur.com/3VoWo1W.jpg','Our Bali Blue Moon coffee is grown in the Kintamani Highlands in Northern Bali. This exquisite bean brews the kind of nuanced, flavorful cup that only comes around once in a blue moon.',
16,16.54,'Light','Asia'),
('Eyes Wide Open','https://i.imgur.com/Pidx5lf.jpg','Life is too short to let your day pass by unnoticed! Carpe that diem and enjoy a mug of Eyes Wide Open coffee while you’re at it.',
15,13.38,'Light','South America')
;
 SELECT * FROM products;